configuration:
  manageAccess:
    - member: bm80177
      role: triage   # Roles: admin, maintain, write, triage, read
    - member: v-bimishra
      role: maintain
    - member: mishrabp
      role: admin
