name: Create a comment on new issue

on: 
  issues:
    types: [opened]

jobs:
  comment-with-actions:
    runs-on: ubuntu-latest
    steps:
      - name: 'Dump GitHub event context (the issue in this case)'
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash

      - name: Create comment with reusable action
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment:
            - With GitHub **Markdown** ✨
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment

  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with GitHub API
        run: |
          gh api -X POST \
            /repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
            -f body='Comment from gh CLI API call!'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ORGANIZATION: ${{ github.repository_owner }}
          REPOSITORY: ${{ github.event.repository.name }}
